/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0

/rat/db/set DETECTOR experiment "dichroic_validation"
/rat/db/set DETECTOR geo_file "dichroic_validation/longpass_boxed.geo"
/rat/db/set GEO[PMT] pos_table "PMTINFO_30DEG"

/run/initialize

/rat/proc count
/rat/procset update 100

/rat/proclast outroot
/rat/procset file "data/transmission_30deg.root"
/tracking/storeTrajectory 1

/generator/add combo gun2:point
/generator/vtx/set opticalphoton 0.8660254037844387 -0.49999999999999994 0 0 1.54875e-06 6.195e-06 0 0 0 10000
/generator/pos/set -0.8660254037844387 0.49999999999999994 0

/generator/rate/set 100
/run/beamOn 1000
