/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0

/rat/db/set DETECTOR experiment "dichroic_validation"
/rat/db/set DETECTOR geo_file "dichroic_validation/control_boxed.geo"

/run/initialize

/rat/proc count
/rat/procset update 10

/rat/proc classifychargebalance

/rat/proclast outroot
/tracking/storeTrajectory 1

/generator/add combo gun2:point
/generator/vtx/set opticalphoton -1 -1 0 0 1.54875e-06 6.195e-06 0 0 0 10000
/generator/pos/set 100 100 0
/generator/rate/set 100

/run/beamOn 1000

## Cut a plane through the detector
#/vis/viewer/addCutawayPlane 0 0 0 cm 1 0 0
#/vis/viewer/addCutawayPlane 0 -100 0 cm 0 1 0
#/vis/viewer/set/viewpointThetaPhi -90 0
#/vis/viewer/zoomTo 10
#/vis/viewer/panTo 10 0
