/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0

/rat/db/set DETECTOR experiment "dichroic_validation"
/rat/db/set DETECTOR geo_file "dichroic_validation/longpass_boxed.geo"

/run/initialize

/rat/proc count
/rat/procset update 10

/rat/proclast outroot
/rat/procset file "data/testOutputName.root"
/tracking/storeTrajectory 1

/generator/add combo gun2:point
# Transmission
# /generator/vtx/set opticalphoton 1 -1 0 0 1.54875e-06 6.195e-06 0 0 0 10000
# /generator/pos/set -100 100 0
# Reflection
# /generator/vtx/set opticalphoton -1 -1 0 0 1.54875e-06 6.195e-06 0 0 0 10000
# /generator/pos/set 100 100 0
# Control, tested that distance between photon source to PMT has no effect on light yield
/generator/vtx/set opticalphoton 1 -1 0 0 1.54875e-06 6.195e-06 0 0 0 10000
/generator/pos/set 1 -1 0

/generator/rate/set 100


/run/beamOn 1000

