/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0

/rat/db/set DETECTOR experiment "dichroic_validation"
/rat/db/set DETECTOR geo_file "dichroic_validation/longpass_boxed.geo"

/rat/db/set GEO[PMT] pos_table "PMTINFO_15DEG"
/run/initialize

/generator/add combo gun2:point
/generator/vtx/set opticalphoton 0.9659258262890683 -0.25881904510252074 0 0 1.54875e-06 6.195e-06 0 0 0 10000
/generator/pos/set -0.9659258262890683 0.25881904510252074 0
/generator/rate/set 100

/vis/open OGLSQt
/vis/scene/create
/vis/scene/add/trajectories rich
/tracking/storeTrajectory 4
/tracking/FillPointCont 1

/vis/scene/add/volume
/vis/scene/add/hits
/vis/sceneHandler/attach

/vis/viewer/set/upVector 0.0 1.0 0.0
/vis/viewer/set/viewpointThetaPhi 0 0

/vis/viewer/zoomTo 50
/vis/viewer/set/style wireframe
/vis/viewer/flush



/run/beamOn 1

## Cut a plane through the detector
#/vis/viewer/addCutawayPlane 0 0 0 cm 1 0 0
#/vis/viewer/addCutawayPlane 0 -100 0 cm 0 1 0
#/vis/viewer/set/viewpointThetaPhi -90 0
#/vis/viewer/zoomTo 10
#/vis/viewer/panTo 10 0
